### ISSUE TITLE
APK: - Attach media bug

### ISSUE THREAD

**Issue by ichpen** [ForumApps/forumappsandroid#3]
New thread ->click attach media->Select file shows All apps associated with this action are blocked or not installed.

**Comment by prathmeshranaut** [comment]
Fixed this in the next build.

**Comment by ichpen** [comment]
Doesn't work with last built sent to me. Check my email but essentially will not allow to create a post with an image. @prathmeshranaut 

I am now able to select local media so that part is fixed.

**Comment by prathmeshranaut** [comment]
Could you send me a screenshot of whats not fixed?

**Comment by ichpen** [comment]
Still cannot upload image from phone, I get this message everytime I hit
post.

[image: Inline image 1]

On Sun, May 21, 2017 at 10:02 AM, Prathmesh Ranaut <notifications@github.com

**Comment by prathmeshranaut** [comment]
Please attach on the github website.

**Comment by ichpen** [comment]
I did but you closed it yesterday.

On Sun, May 21, 2017 at 10:19 AM, Prathmesh Ranaut <notifications@github.com

**Comment by ichpen** [comment]
Reopen: https://github.com/ForumApps/forumappsandroid/issues/3

**Comment by ichpen** [comment]
Issue:

Create new thread, click attach image, select image from phone (I used the Google Photos app), image is shown in the new post but will not let me post it with the message Please wait for attachment to be uploaded. This message does not disappear.

![screenshot_20170521-100418](https://cloud.githubusercontent.com/assets/5346876/26284749/63960204-3e10-11e7-9d8f-ebd5b18ac7e9.png)

**Comment by prathmeshranaut** [comment]
If you wait for a while for the upload to finish. It should finish.

**Comment by prathmeshranaut** [comment]
Probably need a progress bar for slower internet.

**Comment by ichpen** [comment]
I waited an hour :) It isn't working, my internet is silly fast.



On Sun, May 21, 2017 at 10:30 AM, Prathmesh Ranaut <notifications@github.com

**Comment by ichpen** [comment]
But progress bar would definitely help also.

**Comment by prathmeshranaut** [comment]
Let me try it with my account.

**Comment by ichpen** [comment]
Sure thing.

On Sun, May 21, 2017 at 10:34 AM, Prathmesh Ranaut <notifications@github.com
> wrote:

> Let me try it with my account.

**Comment by prathmeshranaut** [comment]
Not working for me either. Will check and let you know.

**Comment by ichpen** [comment]
Thanks.

On Sun, May 21, 2017 at 10:48 AM, Prathmesh Ranaut <notifications@github.com

**Comment by prathmeshranaut** [comment]
This is only a site specific issue. It maybe an addon which is causing the attachments to not be added to the thread. Are there any errors that you can see in the admin area?

**Comment by ichpen** [comment]
No errors in acp
